// Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.
pub const K: u32 = 32;
pub const KEY: [u32; 4] = [0x00000001, 0x00000002, 0x00000003, 0x00000004];
/// (o, h, o_out, h_out)
pub type Step = ([u32; 4], [u32; 4], [u32; 4], [u32; 4]);
pub const T: &[Step] = &[
    (
        [0x00000001, 0x00000002, 0x00000003, 0x00000004],
        [0x00000005, 0x00000006, 0x00000007, 0x00000008],
        [0x00000017, 0x00150007, 0x00000001, 0x00050008],
        [0x9e377ca9, 0x0000e006, 0x02000007, 0x00001820],
    ),
    (
        [0x00000000, 0x00000000, 0x00000000, 0x00000000],
        [0x00000000, 0x00000000, 0x00000000, 0x00000000],
        [0x00000000, 0x00000000, 0x00000000, 0x00000000],
        [0x9e3779b9, 0x00000000, 0x00000000, 0x00000000],
    ),
];
pub const F: &[(u64, [u32; 4], [u32; 4])] = &[
    (
        0,
        [0x472bef12, 0xc0977c66, 0xd330ac3a, 0xb11a020d],
        [0xbfa0b6ba, 0xecdbc48e, 0xf1989116, 0xc2374d96],
    ),
    (
        1,
        [0xb777c10c, 0x2f6b5a5d, 0x67a9ce03, 0x7de06a50],
        [0xd0c2dc4f, 0xe1e50e0f, 0x89efc72c, 0x6e82b062],
    ),
];
pub const STREAM: &[(u64, [u32; 4])] = &[
    (0, [0x0a5bcb90, 0x6dfe98bc, 0x9612198a, 0xac115fd8]),
    (4, [0x33f598d7, 0xb5c280ca, 0x7a8e7b99, 0x8c362290]),
    (32, [0x9da7bac0, 0x4aca79eb, 0xbeb1f65a, 0xe2f0d5a1]),
];
pub const F64: &[(u64, f64)] = &[(0, 0.4296660861094629), (16, 0.2921520424112306)];
pub const F32: &[(u64, f32)] = &[(2, 0.58621365)];
pub const BOOL: &[(u64, bool)] = &[
    (0, false),
    (1, false),
    (2, false),
    (3, false),
    (4, true),
    (5, false),
    (6, false),
    (7, true),
    (128, true),
];
pub const SPLIT0: [u32; 4] = [0xe256e9a1, 0x5020f806, 0x3bd3f7dc, 0x5328763d];
pub const SPLIT1: [u32; 4] = [0xa9ea3f0b, 0x47f97af0, 0xd1844c53, 0x97e9cee2];
pub const FORK0: [u32; 4] = [0x67fd37c5, 0x9dc0b8c6, 0x4e3bd55e, 0xaf3f2216];
pub const PURPOSE7: [u32; 4] = [0x8048398f, 0x1678e814, 0xd8823983, 0xc4b1045c];
pub const SEED: u128 = 42;
pub const SEED_KEY: [u32; 4] = [0x421d21eb, 0x32d31777, 0x62e7564b, 0xdf2bdf82];
pub const SEED_F64: &[(u64, f64)] = &[
    (0, 0.9829130398628935),
    (2, 0.47759300283385586),
    (16, 0.9692135305890753),
];
pub const SEED_U32: &[(u64, u32)] = &[(0, 0x05e80cec)];
