#!/usr/bin/env python3
"""Rust fixtures for tests/derived.rs from tandem-c's cross-check headers, which tandem-c
generates from the shared device core (tandem-cuda core.hpp).

    python3 tools/gen_derived.py ../tandem-c/tests > tests/derived_data/mod.rs
    rustfmt --edition 2024 tests/derived_data/mod.rs
"""
import re
import sys

tests = sys.argv[1]


def read(name):
    with open(f"{tests}/{name}") as f:
        return f.read()


def bounded(text, array, ty, start=False):
    # Entries are `{n, {values}, end_pos}`, or `{start, n, {values}, end_pos}` for fills.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    lead = r"(\d+)ull, " if start else ""
    rows = []
    for m in re.findall(rf"\{{{lead}(\d+)u(?:ll)?,\s*\{{([^}}]*)\}},\s*(\d+)u\}}", body):
        *head, n, vals, end = m
        vals = [v.strip().rstrip("ul") for v in vals.split(",")]
        head = f"{head[0]}, " if head else ""
        rows.append(f"({head}{n}{ty}, &[{', '.join(v + ty for v in vals)}], {end})")
    return ",\n".join(rows)


def exponential(text, array, ty):
    # Entries are `{start, {values}, end_pos}`.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    rows = []
    for start, vals, end in re.findall(r"\{(\d+)ull,\s*\{([^}]*)\},\s*(\d+)u\}", body):
        vals = [v.strip().removesuffix("f") for v in vals.split(",")]
        rows.append(f"({start}, &[{', '.join(v + ty for v in vals)}], {end})")
    return ",\n".join(rows)


below = read("cross_below.h")
fill_below = read("cross_fill_below.h")
normal = read("cross_normal.h")
exp = read("cross_exponential.h")
doubles = re.search(r"CROSS_NORMAL\[[^\]]*\] = \{(.*?)\};", normal, re.S).group(1)
end = re.search(r"CROSS_NORMAL_END_POS = (\d+)u", normal).group(1)
floats = re.search(r"CROSS_NORMALF\[[^\]]*\] = \{(.*?)\};", normal, re.S).group(1).replace("f", "")
endf = re.search(r"CROSS_NORMALF_END_POS = (\d+)u", normal).group(1)

print("// Generated by tools/gen_derived.py from tandem-c's cross-check headers. Do not edit.")
print("// Each case starts from `Tandem::new(42)` after one `next_bool`.\n")
print("/// `(bound, draws, position after)`.")
print(f"pub const BELOW_U32: &[(u32, &[u32], u64)] = &[\n{bounded(below, 'CROSS_U32', 'u32')},\n];\n")
print("/// `(bound, draws, position after)`.")
print(f"pub const BELOW_U64: &[(u64, &[u64], u64)] = &[\n{bounded(below, 'CROSS_U64', 'u64')},\n];\n")
print("/// `normal2()` pairs, flattened, to 17 digits, and the position after.")
print(f"pub const NORMAL_F64: (&[f64], u64) = (&[{doubles.strip()}], {end});")
print("\n/// `normal2f()` pairs, flattened, to 9 digits, and the position after.")
print(f"pub const NORMAL_F32: (&[f32], u64) = (&[{floats.strip()}], {endf});\n")
print("/// `fill_below` cases: `(start position, bound, values, position after)`.")
print(f"pub const FILL_BELOW_U32: &[(u64, u32, &[u32], u64)] = &[\n{bounded(fill_below, 'CROSS_FILL_U32', 'u32', True)},\n];\n")
print(f"pub const FILL_BELOW_U64: &[(u64, u64, &[u64], u64)] = &[\n{bounded(fill_below, 'CROSS_FILL_U64', 'u64', True)},\n];")

print("\n/// `exponential` fills: `(start position, values, position after)`.")
print(f"pub const EXPONENTIAL_F64: &[(u64, &[f64], u64)] = &[\n{exponential(exp, 'CROSS_EXPONENTIAL', 'f64')},\n];\n")
print(f"pub const EXPONENTIAL_F32: &[(u64, &[f32], u64)] = &[\n{exponential(exp, 'CROSS_EXPONENTIALF', 'f32')},\n];")
