#!/usr/bin/env python3
"""Write src/zig_tables.rs, the Float64 normal ziggurat tables, from the spec's table file.

    python3 tools/gen_zig_tables.py ../tandem-spec/tables/normal_f64_zig1024.json > src/zig_tables.rs
    rustfmt --edition 2024 src/zig_tables.rs

The file's SHA-256 must match the value the spec publishes, so a changed table file fails here
instead of changing the normals. Each Float64 is written as its shortest decimal, which Rust
parses back to the same bits.
"""
import hashlib
import json
import sys

SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"
LAYERS = 1024


def f64(s):
    x = float.fromhex(s)
    if x.hex() != s:
        raise SystemExit(f"not a canonical hexadecimal float: {s}")
    r = repr(x)
    return r if "e" in r or "." in r else r + ".0"


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    data = open(sys.argv[1], "rb").read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        raise SystemExit(f"{sys.argv[1]}: SHA-256 {digest}, expected {SHA256}")
    t = json.loads(data)
    if t["layers"] != LAYERS or len(t["W"]) != LAYERS or len(t["K"]) != LAYERS or len(t["Y"]) != LAYERS + 1:
        raise SystemExit("unexpected table sizes")
    w = [f64(s) for s in t["W"]]
    k = [str(int(v)) for v in t["K"]]
    y = [f64(s) for s in t["Y"]]
    print(f"""// Generated by tools/gen_zig_tables.py from the spec's tables/normal_f64_zig1024.json
// (SHA-256 {SHA256}). Do not edit.

/// The base width `R`.
pub(crate) const R: f64 = {f64(t["R"])};

/// The widths `W[i]` for a clear sign bit and `-W[i]` at {LAYERS} + i for a set one, so the index
/// is the low 11 bits of a draw.
pub(crate) static W: [f64; {2 * LAYERS}] = [{", ".join(w + ["-" + s for s in w])}];

/// The fast-path bounds `K[i]` of the 53-bit magnitude.
pub(crate) static K: [u64; {LAYERS}] = [{", ".join(k)}];

/// The density `f(X_i)` at each width, and 1 at the mode.
pub(crate) static Y: [f64; {LAYERS + 1}] = [{", ".join(y)}];""")


if __name__ == "__main__":
    main()
