// Writes tests/derived_data/mod.rs: bounded integers and normals from the shared device core,
// the reference every port agrees with.
//   c++ -std=c++17 -I ../tandem-cuda/include tools/gen_derived.cpp -o gen_derived
//   ./gen_derived > tests/derived_data/mod.rs && rustfmt --edition 2024 tests/derived_data/mod.rs
#include <cstdio>
#include <initializer_list>
#include <tandem/core.hpp>

static const int N = 24;

int main() {
    std::printf("// Generated by tools/gen_derived.cpp from tandem-cuda core.hpp. Do not edit.\n\n");
    std::printf("/// Seed 42, K = 32: `(bound, draws, position after)`.\n");
    std::printf("pub const BELOW_U32: &[(u32, [u32; %d], u64)] = &[\n", N);
    // 0xc0000000 rejects a quarter of the draws, so the loop runs.
    for (uint32_t n : {1u, 3u, 1000u, 0xc0000000u, 0xffffffffu}) {
        tandem::Rng r(42);
        std::printf("(%uu32, [", n);
        for (int i = 0; i < N; i++) std::printf("%u,", r.urand(n));
        std::printf("], %lluu64),\n", (unsigned long long)r.position());
    }
    std::printf("];\n\n/// Seed 42, K = 32: `(bound, draws, position after)`.\n");
    std::printf("pub const BELOW_U64: &[(u64, [u64; %d], u64)] = &[\n", N);
    for (uint64_t n : {1ull, 3ull, 1000000000000ull, 0xc000000000000000ull, ~0ull}) {
        tandem::Rng r(42);
        std::printf("(%lluu64, [", (unsigned long long)n);
        for (int i = 0; i < N; i++) std::printf("%llu,", (unsigned long long)r.urand64(n));
        std::printf("], %lluu64),\n", (unsigned long long)r.position());
    }
    std::printf("];\n\n/// Seed 42, K = 32: bit patterns of `normal()` and the position after.\n");
    std::printf("pub const NORMAL: ([u64; %d], u64) = ([", N);
    tandem::Rng r(42);
    for (int i = 0; i < N; i++) {
        double x = r.normal();
        uint64_t bits;
        std::memcpy(&bits, &x, 8);
        std::printf("0x%016llxu64,", (unsigned long long)bits);
    }
    std::printf("], %lluu64);\n", (unsigned long long)r.position());
}
