#!/usr/bin/env python3
"""Turn the spec's vectors.json into tests/vectors_data/mod.rs, so the tests need no JSON parser.

Usage: tools/gen_vectors.py path/to/vectors.json > tests/vectors_data/mod.rs
Then run rustfmt on the file; CI compares the formatted output.
"""
import json
import sys


def words(ws):
    return "[" + ", ".join(f"0x{w}" for w in ws) + "]"


def main(path):
    v = json.load(open(path))
    out = ["// Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit."]
    out.append(f"pub const K: u32 = {v['K']};")
    out.append(f"pub const KEY: [u32; 4] = {words(v['key'])};")

    out.append("/// (o, h, o_out, h_out)")
    out.append("pub type Step = ([u32; 4], [u32; 4], [u32; 4], [u32; 4]);")
    out.append("pub const T: &[Step] = &[")
    for t in v["T"]:
        out.append(f"    ({words(t['o'])}, {words(t['h'])}, {words(t['o_out'])}, {words(t['h_out'])}),")
    out.append("];")

    out.append("pub const F: &[(u64, [u32; 4], [u32; 4])] = &[")
    for f in v["F"]:
        assert f["domain"] == "DOMAIN_STREAM" and f["aux"] == "AUX_STREAM"
        out.append(f"    ({f['counter']}, {words(f['o'])}, {words(f['h'])}),")
    out.append("];")

    out.append("pub const STREAM: &[(u64, [u32; 4])] = &[")
    for s in v["stream_words"]:
        out.append(f"    ({s['first_word']}, {words(s['words'])}),")
    out.append("];")

    d = v["draws_from_position_0"]
    out.append("pub const F64: &[(u64, f64)] = &[" + ", ".join(f"({k}, {x!r})" for k, x in d["Float64"].items()) + "];")
    out.append("pub const F32: &[(u64, f32)] = &[" + ", ".join(f"({k}, {x!r})" for k, x in d["Float32"].items()) + "];")
    out.append("pub const BOOL: &[(u64, bool)] = &[" + ", ".join(f"({k}, {str(bool(x)).lower()})" for k, x in d["Bool"].items()) + "];")

    k = v["derived_keys"]
    out.append(f"pub const SPLIT0: [u32; 4] = {words(k['split_child_0'])};")
    out.append(f"pub const SPLIT1: [u32; 4] = {words(k['split_child_1'])};")
    out.append(f"pub const FORK0: [u32; 4] = {words(k['fork_child_0_at_block_0'])};")
    out.append(f"pub const PURPOSE7: [u32; 4] = {words(k['purpose_7'])};")

    s = v["seed_whitening"]
    out.append(f"pub const SEED: u128 = {s['seed']};")
    out.append(f"pub const SEED_KEY: [u32; 4] = {words(s['key'])};")
    out.append("pub const SEED_F64: &[(u64, f64)] = &[" + ", ".join(f"({k}, {x!r})" for k, x in s["Float64"].items()) + "];")
    out.append("pub const SEED_U32: &[(u64, u32)] = &[" + ", ".join(f"({k}, 0x{x})" for k, x in s["UInt32"].items()) + "];")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
